name: bus_eka
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  geocoding: ^2.0.1
  geolocator: ^7.6.2
  google_maps_flutter: ^2.0.11
  location: ^4.3.0
  shared_preferences: ^2.0.8
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bus_stop.png
    - assets/images/bus_eka.png
    - assets/images/semi.png
    - assets/images/luxery.png
    - assets/images/book.png
    - assets/images/from.png
    - assets/images/to.png
    - assets/images/bookings.png
    - assets/images/bus_marker.png
    - assets/images/passenger.png
